import * as vscode from "vscode";
import * as cp from "child_process";
import { findLiveServer, logPath, ServerEntry, waitForServer } from "./serverRegistry";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import WebSocket = require("ws");
import { explainFetchError, fetchModels, type DiscoverableBackend } from "./modelList";
import { loadSiteConfig, compareVersions, resolveReleaseRoot } from "./release";

let serverProcess: cp.ChildProcess | undefined;

// Set once the server reports it has detached. From then on it is not ours to end: it
// re-pointed its output away from the pipe we hold and left our process group precisely
// so that closing this window leaves it working. Module-global beside `serverProcess`
// because the two are answers to the same question — who owns this process — and
// `deactivate()` reads both.
let serverDetached = false;

// The timer mirroring a server's log into its output channel, reachable from
// `deactivate()`.
let _stopLogTail: vscode.Disposable | undefined;

/** fsPath of this extension's install root, captured at activation. */
let extensionRoot: string | undefined;

/** Global-state key holding the endpoint the user asked us to remember. */
const REMEMBERED_KEY = "mimir.rememberedEndpoint";

/**
 * Backends reached at an address the user types — so they can be remembered,
 * reconnected to unattended, and asked for their model list. Anthropic is absent:
 * it needs a key we deliberately never persist.
 */
const ADDRESSED_BACKENDS: string[] = ["vllm", "ray", "ollama"];

/** Endpoint we can reconnect to unattended — no secret is ever part of it. */
interface RememberedEndpoint {
  backend: string;
  baseUrl: string;
  model: string;
}

/**
 * Root of this site's shared release tree, when one is present.
 *
 * Returns "" on machines without the tree (the `current` symlink is the
 * presence probe), so every following resolution step falls through unchanged
 * and the extension behaves exactly as before anywhere but the cluster.
 */
function releaseRoot(): string {
  const configured = vscode.workspace.getConfiguration("mimir").get<string>("releaseHome");
  // An explicit setting wins; otherwise a deployment may ship the path in the
  // extension's site.json (generated by the site's own build tooling — never
  // committed upstream, so nothing here is site-specific). Empty and unset are
  // the same thing — the declared default "" must not mask site.json (see
  // resolveReleaseRoot; until 1.1.2 it did, via ??).
  const fromSite = extensionRoot ? loadSiteConfig(extensionRoot, (p) => fs.readFileSync(p, "utf8"))?.releaseHome : undefined;
  const root = resolveReleaseRoot(configured, fromSite);
  return root && fs.existsSync(path.join(root, "current")) ? root : "";
}

/** Interpreter recorded for the current shared release, or "" when there is none. */
function sharedReleasePython(): string {
  const root = releaseRoot();
  if (!root) return "";
  try {
    const p = fs.readFileSync(path.join(root, "current", "PYTHON_COMMAND"), "utf8").trim();
    return p && fs.existsSync(p) ? p : "";
  } catch {
    return "";
  }
}

/**
 * Interpreter that runs the WS server.
 *
 * `bash -c` is neither a login nor an interactive shell, so it sources no profile:
 * the child gets this extension host's environment and nothing else. `python3` from
 * that PATH is therefore whatever the machine's default is — frequently older than
 * MIMIR's 3.10 minimum, and almost never the venv the package was installed into.
 *
 * Rather than making every user write a setting, resolve it in order:
 *   1. `mimir.pythonPath` — an explicit override still wins.
 *   2. `MIMIR_PYTHON` — for people who would rather export it than click.
 *   3. `<releaseHome>/current/PYTHON_COMMAND` — part of a shared site release:
 *      every user of the cluster runs the current release with no configuration
 *      of their own. Ignored where the release tree does not exist.
 *   4. `<state home>/python` — written by install.sh, so a plain `./install.sh`
 *      needs no configuration at all.
 *   5. `python3` from PATH.
 */
function resolvePython(): string {
  const configured = vscode.workspace.getConfiguration("mimir").get<string>("pythonPath");
  if (configured) {
    return configured;
  }
  if (process.env.MIMIR_PYTHON) {
    return process.env.MIMIR_PYTHON;
  }
  const shared = sharedReleasePython();
  if (shared) {
    return shared;
  }
  const stateHome = process.env.MIMIR_STATE_HOME || path.join(os.homedir(), ".mimir");
  try {
    const interpreter = fs.readFileSync(path.join(stateHome, "python"), "utf8").trim();
    if (interpreter && fs.existsSync(interpreter)) {
      return interpreter;
    }
  } catch {
    // Not installed via install.sh, or the file was removed — fall through.
  }
  return "python3";
}

/**
 * Environment the MIMIR server process is spawned with.
 *
 * The extension host inherits the user's login-shell environment — on
 * Remote-SSH it is resolved from that shell at connection — and two of its
 * variables poison any interpreter they reach. `PYTHONHOME` (exported by some
 * module systems and setup snippets) overrides the interpreter's own home, so
 * the shared venv's python runs on the user's stdlib and site-packages, or
 * refuses to start outright; `PYTHONPATH` puts the user's packages ahead of
 * the venv's in `sys.path`. Either one makes MIMIR "use the user's python"
 * although the right binary was launched.
 *
 * Both are dropped here, for the processes MIMIR starts and nothing else. The
 * user's shell is never touched (the 1.0.0 pollution fix promised as much),
 * and nothing the user runs through the agent loses them: the bash tool
 * already rebuilds a minimal environment for every command it executes.
 */
function mimirServerEnv(): NodeJS.ProcessEnv {
  const env = { ...process.env };
  delete env.PYTHONHOME;
  delete env.PYTHONPATH;
  return env;
}

/**
 * Update this extension from the shared release when it ships a newer version.
 *
 * Runs at most once per window (called from activate), never blocks startup, and
 * is a no-op on machines without the release tree. Downgrades are deliberately
 * ignored: `current` may be rolled back to an older release, and the extension
 * must not fight that. On success the user is invited to reload the window to
 * switch to the newly installed code.
 */
function maybeSelfUpdate(context: vscode.ExtensionContext): void {
  const root = releaseRoot();
  if (!root) return;
  let marker: string;
  try {
    marker = fs.readFileSync(path.join(root, "current", "EXTENSION_VERSION"), "utf8").trim();
  } catch {
    return; // the marker is written by deploy/release.sh — no release mode here.
  }
  const installed = String(context.extension.packageJSON.version ?? "0.0.0");
  if (!marker || compareVersions(marker, installed) <= 0) return;
  const vsix = path.join(root, "current", "vsix", `mimir-${marker}.vsix`);
  if (!fs.existsSync(vsix)) {
    void vscode.window.showInformationMessage(
      `MIMIR ${marker} is available — install it manually (Extensions → Install from VSIX…):\n${vsix}`
    );
    return;
  }
  void vscode.window
    .withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: `Updating the MIMIR extension to ${marker}…`,
      },
      () => vscode.commands.executeCommand("workbench.extensions.installExtension", vscode.Uri.file(vsix))
    )
    .then(
      () => {
        const reload = "Reload Window";
        void vscode.window
          .showInformationMessage(`MIMIR extension updated to ${marker}.`, reload)
          .then((choice) => {
            if (choice === reload) {
              void vscode.commands.executeCommand("workbench.action.reloadWindow");
            }
          });
      },
      (err: unknown) => console.warn("MIMIR: automatic extension update failed:", err)
    );
}

/**
 * Append the host of *baseUrl* to the inherited no_proxy/NO_PROXY lists.
 *
 * On-prem vLLM hosts are reachable directly but an HTTP proxy will
 * black-hole them, which turns model resolution into an indefinite hang.
 */
function noProxyFor(baseUrl: string): Record<string, string> {
  let host: string;
  try {
    host = new URL(baseUrl).hostname;
  } catch {
    return {};
  }
  if (!host) {
    return {};
  }
  const merge = (v: string | undefined) => (v ? `${v},${host}` : host);
  return { no_proxy: merge(process.env.no_proxy), NO_PROXY: merge(process.env.NO_PROXY) };
}

// ── Virtual document provider for proposed file content (diff editor) ─────────

/** Stores proposed file content keyed by virtual URI path, for open_diff. */
const _diffProposedContent = new Map<string, string>();

/**
 * Reconstruct the "before" content by reverse-applying a unified diff patch.
 * Removes added lines (+) and restores removed lines (-) to recover the original.
 */
function _reversePatch(current: string, patch: string): string {
  const currentLines = current.split("\n");
  const result: string[] = [];
  const patchLines = patch.split("\n");

  let ci = 0; // index into currentLines

  for (let pi = 0; pi < patchLines.length; pi++) {
    const line = patchLines[pi];
    if (line.startsWith("---") || line.startsWith("+++") || line.startsWith("diff ")) continue;
    if (line.startsWith("@@")) {
      // @@ -oldStart,oldCount +newStart,newCount @@
      const m = line.match(/\+(\d+)(?:,(\d+))?/);
      if (m) {
        const newStart = parseInt(m[1], 10) - 1; // 0-based
        // Emit unchanged lines up to this hunk from current
        while (ci < newStart) {
          result.push(currentLines[ci++]);
        }
      }
      continue;
    }
    if (line.startsWith("+")) {
      // Line was added in the patch → skip it in the current (it exists there)
      ci++;
    } else if (line.startsWith("-")) {
      // Line was removed in the patch → restore it to the original
      result.push(line.slice(1));
    } else if (line.startsWith(" ")) {
      // Context line — present in both; advance current pointer
      result.push(currentLines[ci++]);
    }
  }
  // Emit any remaining lines after the last hunk
  while (ci < currentLines.length) {
    result.push(currentLines[ci++]);
  }
  return result.join("\n");
}

const _diffContentProvider = new class implements vscode.TextDocumentContentProvider {
  provideTextDocumentContent(uri: vscode.Uri): string {
    return _diffProposedContent.get(uri.path) ?? "";
  }
}();

// ── Plan preview: our own panel, rendered from the bytes on disk ─────────────
//
// VS Code's Markdown preview renders a cached TextDocument, and nothing we can
// call makes it re-read a given revision on demand: previewing the plan file
// misses updates when the watcher does not fire (network mount), and previewing
// a virtual document races the model update — the refresh often re-renders the
// previous plan. Three rounds of invalidate/await/refresh narrowed that race
// without closing it. So the plan is not previewed through a document at all:
// each show reads the file, renders it with the Markdown extension's own engine
// (`markdown.api.render`) and writes the HTML into a panel we own. What is on
// screen is whatever was read last, by construction.
//
// One panel for every plan: a new plan (new title → new file) replaces the
// content of the same tab rather than opening another.
//
// A webview has no notion of the plan's folder, so what the preview used to
// resolve for us is done here: relative image paths are rewritten to webview
// URIs (and their folders allowed), and a small script hands link clicks back
// to the extension, which resolves them against the plan's folder.

/** The plan panel, while it is open. */
let _planPanel: vscode.WebviewPanel | undefined;

/** Absolute path of the plan the panel currently mirrors. */
let _currentPlanPath: string | undefined;

/** Bumped on every render, so a slow render cannot overwrite a newer one. */
let _planRenderSeq = 0;

function _escapeHtml(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]!));
}

/** The Markdown extension's folder, for its preview stylesheet. */
function _markdownMediaUri(): vscode.Uri | undefined {
  const ext = vscode.extensions.getExtension("vscode.markdown-language-features");
  return ext ? vscode.Uri.joinPath(ext.extensionUri, "media") : undefined;
}

/** True for `https:`, `data:`, `vscode-resource:`… and protocol-relative URLs. */
function _hasScheme(ref: string): boolean {
  return /^[a-z][\w+.-]*:/i.test(ref) || ref.startsWith("//");
}

/** `ref` from the plan, as an absolute path (fragment and query dropped). */
function _resolveFromPlan(ref: string, planAbs: string): string {
  let p = ref.replace(/[?#].*$/, "");
  try {
    p = decodeURI(p);
  } catch {
    /* keep it as written */
  }
  return path.isAbsolute(p) ? p : path.join(path.dirname(planAbs), p);
}

/**
 * Point every local `<img src>` at a webview URI. Returns the rewritten HTML and
 * the folders those images live in, which the panel must be allowed to read.
 */
function _rewriteImages(html: string, planAbs: string, webview: vscode.Webview): { html: string; dirs: string[] } {
  const dirs = new Set<string>();
  const out = html.replace(/(<img\b[^>]*?\bsrc=")([^"]*)(")/gi, (all, pre: string, src: string, post: string) => {
    if (!src || _hasScheme(src)) return all;
    const abs = _resolveFromPlan(src.replace(/&amp;/g, "&"), planAbs);
    dirs.add(path.dirname(abs));
    return pre + webview.asWebviewUri(vscode.Uri.file(abs)).toString() + post;
  });
  return { html: out, dirs: [...dirs] };
}

/** Follow a link clicked in the plan panel. In-page anchors never get here. */
function _openPlanLink(href: string): void {
  const planAbs = _currentPlanPath;
  if (_hasScheme(href) && !/^file:/i.test(href)) {
    void vscode.env.openExternal(vscode.Uri.parse(href));
    return;
  }
  if (!planAbs) return;
  const abs = /^file:/i.test(href) ? vscode.Uri.parse(href).fsPath : _resolveFromPlan(href, planAbs);
  if (!fs.existsSync(abs)) {
    void vscode.window.showWarningMessage(`MIMIR: ${abs} not found`);
    return;
  }
  if (fs.statSync(abs).isDirectory()) {
    void vscode.commands.executeCommand("revealInExplorer", vscode.Uri.file(abs));
    return;
  }
  vscode.workspace.openTextDocument(vscode.Uri.file(abs)).then(
    (doc) => vscode.window.showTextDocument(doc, { preview: true, viewColumn: vscode.ViewColumn.One }),
    () => vscode.commands.executeCommand("vscode.open", vscode.Uri.file(abs))
  );
}

/** Hands link clicks to the extension; scrolls in-page anchors itself. */
const _PLAN_SCRIPT = `
const vscode = acquireVsCodeApi();
document.addEventListener("click", (e) => {
  const a = e.target.closest && e.target.closest("a[href]");
  if (!a) return;
  const href = a.getAttribute("href");
  e.preventDefault();
  if (href.startsWith("#")) {
    const id = decodeURIComponent(href.slice(1));
    const el = document.getElementById(id) || document.getElementsByName(id)[0];
    if (el) el.scrollIntoView();
    return;
  }
  vscode.postMessage({ type: "open", href });
});`;

/** Read the current plan from disk and write it into the panel. */
async function _renderPlan(): Promise<void> {
  const panel = _planPanel;
  const abs = _currentPlanPath;
  if (!panel || !abs) return;
  const seq = ++_planRenderSeq;
  let body: string;
  try {
    const text = fs.readFileSync(abs, "utf8");
    try {
      body = await vscode.commands.executeCommand<string>("markdown.api.render", text);
    } catch {
      // Markdown extension disabled: the plan is still readable as text.
      body = `<pre>${_escapeHtml(text)}</pre>`;
    }
  } catch (e) {
    body = `<p>Cannot read ${_escapeHtml(abs)}</p><pre>${_escapeHtml(String(e))}</pre>`;
  }
  if (seq !== _planRenderSeq || panel !== _planPanel) return;
  const media = _markdownMediaUri();
  const images = _rewriteImages(body, abs, panel.webview);
  // Roots before html: the new page must be allowed to load what it references.
  panel.webview.options = {
    enableScripts: true,
    localResourceRoots: [
      ...(media ? [media] : []),
      vscode.Uri.file(path.dirname(abs)),
      ...images.dirs.map((d) => vscode.Uri.file(d)),
    ],
  };
  const sheets = media
    ? ["markdown.css", "highlight.css"]
        .map((f) => `<link rel="stylesheet" href="${panel.webview.asWebviewUri(vscode.Uri.joinPath(media, f))}">`)
        .join("\n")
    : "";
  const csp = panel.webview.cspSource;
  const nonce = Math.random().toString(36).slice(2) + Date.now().toString(36);
  panel.title = `Plan — ${path.basename(abs, path.extname(abs))}`;
  panel.webview.html = `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${csp} 'unsafe-inline'; img-src ${csp} https: data:; script-src 'nonce-${nonce}';">
${sheets}
<style>body { padding: 0 26px; font-family: var(--vscode-markdown-font-family, var(--vscode-font-family)); font-size: var(--vscode-markdown-font-size, 14px); }</style>
</head><body class="vscode-body">${images.html}
<script nonce="${nonce}">${_PLAN_SCRIPT}</script></body></html>`;
}

/** Poller for the plan the panel shows, if any. */
let _previewWatch: { path: string; mtimeMs: number; size: number; timer: NodeJS.Timeout } | undefined;

function _stopPreviewWatch(): void {
  if (_previewWatch) {
    clearInterval(_previewWatch.timer);
    _previewWatch = undefined;
  }
}

/** Poll `abs` and re-render the panel whenever the file changes on disk. */
function _watchPreviewedFile(abs: string): void {
  const stamp = (): { mtimeMs: number; size: number } => {
    try {
      const st = fs.statSync(abs);
      return { mtimeMs: st.mtimeMs, size: st.size };
    } catch {
      return { mtimeMs: 0, size: -1 };
    }
  };
  _stopPreviewWatch();
  const timer = setInterval(() => {
    if (!_previewWatch) return;
    const now = stamp();
    if (now.mtimeMs !== _previewWatch.mtimeMs || now.size !== _previewWatch.size) {
      Object.assign(_previewWatch, now);
      void _renderPlan();
    }
  }, 1000);
  _previewWatch = { path: abs, ...stamp(), timer };
}

/** Show `abs` in the plan panel, opening the panel if needed. */
function _showPlanPreview(abs: string): void {
  _currentPlanPath = abs;
  if (!_planPanel) {
    const media = _markdownMediaUri();
    _planPanel = vscode.window.createWebviewPanel(
      "mimir.plan",
      "Plan",
      // Active, not Beside: the chat lives in the side bar, so "beside" meant beside
      // the editor group — splitting the editor area in two and leaving the plan half
      // a window wide. The plan is a document to read, so it opens as a tab in the
      // group already there and fills it. Focus comes with it, or the tab would open
      // behind the file the user was reading and look like nothing had happened.
      { viewColumn: vscode.ViewColumn.Active, preserveFocus: false },
      { enableScripts: true, localResourceRoots: media ? [media] : [] }
    );
    _planPanel.webview.onDidReceiveMessage((m) => {
      if (m?.type === "open" && typeof m.href === "string") _openPlanLink(m.href);
    });
    _planPanel.onDidDispose(() => {
      _planPanel = undefined;
      _stopPreviewWatch();
    });
  } else {
    // Same reasoning: an existing panel is brought to the front of its group rather
    // than left behind whatever tab is on top of it.
    _planPanel.reveal(undefined, false);
  }
  // Re-baseline the poller before the read, so a write landing in between is
  // caught on the next tick rather than lost.
  _watchPreviewedFile(abs);
  void _renderPlan();
}

export function activate(context: vscode.ExtensionContext): void {
  extensionRoot = context.extensionUri.fsPath;
  context.subscriptions.push(
    vscode.workspace.registerTextDocumentContentProvider("mimir-diff", _diffContentProvider)
  );

  const provider = new MimirAgentViewProvider(context.extensionUri, context.globalState);
  context.subscriptions.push(
    vscode.window.registerWebviewViewProvider("mimir.chatView", provider, {
      webviewOptions: { retainContextWhenHidden: true },
    })
  );

  // `onStartupFinished` activates us with the chat panel possibly still closed,
  // so the remembered endpoint is probed here rather than on the first view
  // resolve: MIMIR is already connected by the time the user opens the panel.
  void provider.maybeAutoConnect();

  // Shared-release mode: offer to pick up the current release's extension when
  // it is newer than the one installed. No-op where the release tree is absent.
  maybeSelfUpdate(context);

  // Active-editor context: tell the webview which file (and selected line range)
  // is focused, so the user can attach it to a message with one click (opt-in chip).
  // Selection changes are debounced to avoid a flood while dragging.
  let selectionTimer: ReturnType<typeof setTimeout> | undefined;
  const pushEditor = () => provider.pushActiveEditor();
  context.subscriptions.push(
    vscode.window.onDidChangeActiveTextEditor(pushEditor),
    vscode.window.onDidChangeTextEditorSelection(() => {
      if (selectionTimer) clearTimeout(selectionTimer);
      selectionTimer = setTimeout(pushEditor, 120);
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("mimir.openChat", () =>
      vscode.commands.executeCommand("mimir.chatView.focus")
    )
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("mimir.startServer", () =>
      startServer(context)
    )
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("mimir.stopServer", () => stopServer())
  );
}

export function deactivate(): void {
  _stopPreviewWatch();
  // The server is deliberately left running when detached; an interval in a disposed
  // extension host is the one part of that which must not survive.
  _stopLogTail?.dispose();
  // A detached server is left running on purpose — that is the whole point of having
  // asked. Killing it here would make "continue without me" mean nothing at the one
  // moment it is supposed to take effect.
  if (!serverDetached) serverProcess?.kill();
  serverProcess = undefined;
}

// ── Sidebar WebviewViewProvider ───────────────────────────────────────────────

class MimirAgentViewProvider implements vscode.WebviewViewProvider {
  private _ws: WebSocket | undefined;
  private _view: vscode.WebviewView | undefined;
  private _pendingMessages: string[] = [];
  /** An auto-connect is already running (or has run) — never start a second one. */
  private _autoConnectStarted = false;
  /** A probe is in flight; a view resolving meanwhile must not fire its own. */
  private _autoConnectProbing = false;
  /**
   * Bumped by every new connect attempt. A retry chain carries the generation it
   * was born with, so the one a superseded attempt left running goes inert instead
   * of reclaiming `_ws` and then reporting the connection closed.
   */
  private _connectGen = 0;
  /**
   * Log channel of an active `mimir.wsUrl` attach, or undefined when we spawned the
   * server ourselves. Kept so a failed attach can name the setting responsible.
   */
  private _attachLog: vscode.OutputChannel | undefined;
  /** Stops the timer mirroring a server's log file into its output channel. */
  private _logTail: vscode.Disposable | undefined;
  /**
   * Log channel for model-discovery results, created on first use. The connect
   * form probes the endpoint before any server is started, so this cannot rely
   * on the per-connect channel existing.
   */
  private _modelLog: vscode.OutputChannel | undefined;
  /**
   * Which model probe the webview is still waiting on. A probe now waits up to
   * 30 s, and the form fires one per address the user pauses on: a slow reply for
   * an address that has since been retyped would otherwise land last and replace
   * a good list with its own failure. Only the newest probe may post.
   */
  private _modelProbeSeq = 0;
  /**
   * Endpoint we auto-connected to, kept until a webview has actually been told.
   * The React app is what shows the connecting state, and it mounts long after we
   * start — so this is replayed on every `get_config` (its mount handshake) until
   * the socket is up.
   */
  private _pendingAutoConnect: RememberedEndpoint | undefined;
  /**
   * The model list the auto-connect probe already received, kept for the webview.
   *
   * The probe asks the endpoint what it serves and used to weigh only whether it
   * answered at all. But the status bar's model picker appears when the endpoint
   * reported a real choice, and on an auto-connect nothing else ever asks: the
   * connect form is the only other caller and it is never shown. So a remembered
   * endpoint came up connected with the list already fetched, thrown away, and the
   * model rendered as a static label — no way to switch, on a server serving
   * several. Replayed on `get_config` rather than posted once, because the React
   * app usually does not exist yet when the probe answers.
   */
  private _autoConnectModels: { backend: string; models: string[] } | undefined;
  /**
   * Address of the server this window talks to, learned from the server's own
   * "Listening on ws://…" line (it binds an OS-assigned port, so each VS Code
   * window gets its own) or copied from the `mimir.wsUrl` override. Every
   * reconnect goes through this — there is no fixed address to fall back on.
   */
  private _wsUrl: string | undefined;

  constructor(
    private readonly extensionUri: vscode.Uri,
    private readonly memento: vscode.Memento,
  ) {}

  resolveWebviewView(view: vscode.WebviewView): void {
    this._view = view;
    view.webview.options = {
      enableScripts: true,
      localResourceRoots: [
        vscode.Uri.joinPath(this.extensionUri, "dist"),
        vscode.Uri.joinPath(this.extensionUri, "images"),
      ],
    };
    view.webview.html = getWebviewHtml(view.webview, this.extensionUri);

    // Messages from the React app → forward to Python WS server
    view.webview.onDidReceiveMessage((msg: unknown) => {
      this._handleFromWebview(msg);
    });

    // No blind auto-connect: nothing is started unless the user ticked "Remember
    // this address" and that address answers (see _maybeAutoConnect). This keeps
    // us from spawning connections on HPC front nodes.

    // Send config immediately so the webview can populate the model list.
    void this._sendConfig();
    // Seed the active-file chip on (re)load.
    this.pushActiveEditor();

    // Reconnect on our own to the address the user asked us to remember (a no-op
    // when activation already started it, or nothing is stored). Catching a
    // webview up on a connect it never saw is *not* done here: nothing posted
    // from `resolveWebviewView` is guaranteed to be heard, because the React app
    // has not loaded its message listener yet. That happens on `get_config`, the
    // handshake the app sends once it is mounted (see `_resumeAutoConnect`).
    void this._maybeAutoConnect();
  }

  /**
   * Reconnect to the remembered address, if it answers.
   *
   * The user opts in with the "Remember this address" checkbox in the connect
   * form; we store backend/address/model (never a key) in global state. Once per
   * window — at activation, so an unopened chat panel still comes up connected —
   * we probe the endpoint's model list, the same request the form makes, and
   * only start the server when it replies. An unreachable address (laptop off
   * the VPN, compute node released) is not an error here: the connect form
   * simply comes up as usual, pre-filled.
   */
  async maybeAutoConnect(): Promise<void> {
    return this._maybeAutoConnect();
  }

  private async _maybeAutoConnect(): Promise<void> {
    if (this._autoConnectStarted || this._autoConnectProbing) return;

    // A server this workspace already has comes first, and it does not depend on a
    // remembered address: a run left going when the window closed is still serving,
    // and the point of leaving it there is that reopening the window finds it. Asked
    // before the endpoint probe because it is both cheaper and more certain — the
    // probe asks whether an LLM endpoint answers, this asks whether the agent that was
    // already working is still working.
    if (await this._attachToRunningServer()) return;

    const saved = this._remembered();
    if (!saved) return;

    const verifySsl = vscode.workspace.getConfiguration("mimir").get<boolean>("vllmVerifySsl", true);
    this._autoConnectProbing = true;
    try {
      // Longer than the form's own probe is short: nothing waits on this — the
      // connect form is already usable — and the address is one that worked
      // before, so a slow VPN or a still-starting node is worth waiting out.
      const models = await fetchModels(
        saved.backend as DiscoverableBackend, saved.baseUrl, verifySsl, 30000);
      this._autoConnectModels = { backend: saved.backend, models };
    } catch {
      // Endpoint not up — leave the user on the connect form. The attempt is not
      // marked as started, so opening the chat panel later probes once more: at
      // VS Code startup the network (VPN, compute node) is often not up yet.
      return;
    } finally {
      this._autoConnectProbing = false;
    }
    // The user can have been impatient and connected by hand while we probed
    // (the server spawns before the socket exists, so check both).
    if (this._ws || (serverProcess && !serverProcess.killed)) return;
    this._autoConnectStarted = true;

    // Replayed on the webview's `get_config` until the socket is up, because the
    // React app may not be listening yet (or may not exist at all).
    this._pendingAutoConnect = saved;
    this._announceAutoConnect();
    // Both here and on `get_config`, because neither alone covers it: the webview
    // may not exist yet when the probe answers, and the probe may not have answered
    // yet when the webview mounts. Posting the list twice costs a state set.
    this._announceModels();
    // Startup connect: don't pop the server log over whatever the user opened.
    void this._startServerAndConnect(
      saved.model, saved.backend, saved.baseUrl, "", { silent: true },
    ).catch((err) => {
      // Reported rather than swallowed: a rejection here leaves the panel on
      // "connecting" with nothing said about why.
      vscode.window.createOutputChannel("MIMIR Server").appendLine(
        `Starting the server failed: ${err instanceof Error ? err.message : String(err)}`);
      this._pendingAutoConnect = undefined;
      this._view?.webview.postMessage({ type: "ws_closed" });
    });
  }

  /**
   * Attach to the server this workspace already has, if it has one.
   *
   * Reuses the attach path `mimir.wsUrl` has always taken: nothing is started, so
   * `serverProcess` stays undefined and this server is never torn down — it is not
   * ours to kill. That is exactly the right relationship with a server that was
   * deliberately left running.
   *
   * Returns whether it attached, so the caller can skip the connect form entirely:
   * a window that reopens on a live run must not ask the user to connect to it.
   */
  private async _attachToRunningServer(
    { silent = true }: { silent?: boolean } = {},
  ): Promise<boolean> {
    if (this._ws || (serverProcess && !serverProcess.killed)) return false;
    // An explicit override is the user's own statement about where the server is, and
    // it wins: the spawn path already defers to it for the same reason.
    const override = (vscode.workspace.getConfiguration("mimir")
      .get<string>("wsUrl") ?? "").trim();
    if (override) return false;

    const cwd = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? process.cwd();
    let entry: ServerEntry | undefined;
    try {
      entry = await findLiveServer(cwd);
    } catch {
      return false;   // advisory, never authoritative
    }
    if (!entry) return false;

    const log = vscode.window.createOutputChannel("MIMIR Server");
    if (!silent) log.show();
    log.appendLine(
      `Attaching to the MIMIR server already running for this workspace ` +
      `(${entry.url}, pid ${entry.pid}). It was not started by this window, so it is ` +
      `left running when the window closes. Starting a second server for one ` +
      `workspace would have both write the same session journal.`
    );
    this._attachLog = log;
    this._autoConnectStarted = true;
    // So a webview that mounts after this shows "connecting" rather than the form.
    this._pendingAutoConnect = {
      backend: "", baseUrl: entry.url, model: entry.model ?? "",
    } as { backend: string; baseUrl: string; model: string };
    this._announceAutoConnect();
    this._wsUrl = entry.url;
    this._connectToServer(entry.url);
    return true;
  }

  /**
   * Notice the server telling us it has detached.
   *
   * Nothing is rendered: the point is the ownership change. The server has re-pointed
   * its output away from the pipe we hold and left our process group, so from here on
   * closing this window leaves it working — which is what the user asked for. Read in
   * the host rather than the webview because it is the host that does the killing.
   */
  private _noteOwnership(text: string): void {
    let msg: {
      type?: string; pid?: number; autonomy?: string; log?: string | null;
      detached?: boolean;
    };
    try {
      msg = JSON.parse(text);
    } catch {
      return;
    }
    if (msg?.type !== "detached") return;
    const log = vscode.window.createOutputChannel("MIMIR Server");
    // Absent means detached: an older server sends no flag, and the message existed
    // only to announce a detachment.
    if (msg.detached === false) {
      serverDetached = false;
      log.appendLine(
        `This server belongs to this window again (pid ${msg.pid ?? "?"}); closing ` +
        `the window stops it.`
      );
      return;
    }
    serverDetached = true;
    log.appendLine(
      `This server has detached (pid ${msg.pid ?? "?"}, autonomy ` +
      `${msg.autonomy ?? "?"}). It is left running when the window closes; its ` +
      `output continues in ${msg.log ?? "its log"}.`
    );
  }

  /** Hand the webview the model list the auto-connect probe already has. */
  private _announceModels(): void {
    if (!this._view || !this._autoConnectModels) return;
    this._view.webview.postMessage({ type: "models", ...this._autoConnectModels });
  }

  /** Tell the webview, if there is one, which endpoint we are connecting to. */
  private _announceAutoConnect(): void {
    if (!this._view || !this._pendingAutoConnect) return;
    this._view.webview.postMessage({ type: "auto_connect", ...this._pendingAutoConnect });
  }

  /**
   * Bring a freshly mounted webview up to date with a connection it never saw.
   *
   * Called from the `get_config` handshake — the first moment the React app is
   * known to be listening. Two cases: the connect is still in flight (replay
   * `auto_connect`, so the app shows the connecting state instead of the form),
   * or the socket is already live and its `ready` greeting went to a webview that
   * did not exist. The Python server greets every new client, so re-attaching is
   * what moves the UI to "connected".
   */
  private _resumeAutoConnect(): void {
    if (!this._pendingAutoConnect) return; // nothing was missed — leave the socket alone
    this._announceAutoConnect();
    const live = this._ws;
    if (live && this._wsUrl) {
      this._ws = undefined; // so the close below drives no retry/teardown
      live.close();
      this._connectToServer(this._wsUrl);
    }
    // The webview has now heard it — replaying again would throw a connected UI
    // back into "connecting" and needlessly cycle a healthy socket.
    this._pendingAutoConnect = undefined;
  }

  /** The remembered endpoint, or undefined when nothing valid is stored. */
  private _remembered(): RememberedEndpoint | undefined {
    const saved = this.memento.get<RememberedEndpoint>(REMEMBERED_KEY);
    if (!saved || !saved.baseUrl) return undefined;
    // Only endpoints the user gives an address for; Anthropic needs a key we
    // deliberately never persist, so it can't be auto-connected.
    if (!ADDRESSED_BACKENDS.includes(saved.backend)) return undefined;
    return saved;
  }

  /**
   * Report the active editor's file + selected line range to the webview as an
   * ``active_editor`` message. The webview shows a click-to-attach chip. When no file
   * editor is active we keep the last value (webview focus / non-file panels shouldn't
   * clear the chip), so nothing is posted in that case.
   */
  pushActiveEditor(): void {
    const editor = vscode.window.activeTextEditor;
    if (!editor || editor.document.uri.scheme !== "file") return;

    const file = vscode.workspace.asRelativePath(editor.document.uri, false);
    const sel = editor.selection;
    let selection: string | null = null;
    if (sel && !sel.isEmpty) {
      const start = sel.start.line + 1;
      // A selection ending at column 0 of a line doesn't really include that line
      // (whole-line drag selection), so treat it as ending on the previous line.
      const last =
        sel.end.character === 0 && sel.end.line > sel.start.line
          ? sel.end.line
          : sel.end.line + 1;
      selection = start === last ? `${start}` : `${start}-${last}`;
    }
    this._view?.webview.postMessage({ type: "active_editor", file, selection });
  }

  /**
   * Seed the connect form with the defaults from settings.
   *
   * Only the starting values: the user edits the address in the form, and the
   * model list comes from the endpoint itself (see `_sendModels`), so a working
   * setup needs no `.vscode/settings.json` at all.
   */
  private async _sendConfig(): Promise<void> {
    const cfg = vscode.workspace.getConfiguration("mimir");

    // Whether this workspace already has a server, so a disconnected panel can offer
    // to rejoin it rather than asking for an endpoint it will not use. A run left
    // going is the one thing the user came back for, and a connect form is a poor way
    // to say "it is still here".
    let running: ServerEntry | undefined;
    try {
      const cwd = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? process.cwd();
      running = await findLiveServer(cwd);
    } catch {
      running = undefined;
    }

    this._view?.webview.postMessage({
      type: "config",
      running: running
        ? { url: running.url, pid: running.pid, model: running.model ?? "",
            autonomy: running.autonomy ?? "", detached: running.detached === true }
        : null,
      backend: cfg.get<string>("backend") ?? "vllm",
      vllmBaseUrl: cfg.get<string>("vllmBaseUrl") ?? "http://127.0.0.1:8000",
      rayBaseUrl: cfg.get<string>("rayBaseUrl") ?? "http://127.0.0.1:8000",
      ollamaBaseUrl: cfg.get<string>("ollamaUrl") ?? "http://127.0.0.1:11434",
      anthropicModels: cfg.get<string[]>("anthropicAvailableModels") ?? [],
      remembered: this._remembered() ?? null,
    });
  }

  /**
   * Open the socket to *wsUrl*, retrying while the server is still coming up.
   *
   * *gen* identifies the attempt. Omit it to start a new one — that supersedes
   * any attempt already in flight, whose retries then find a newer generation and
   * stop. Without that, a chain still retrying the previous server's port would
   * reassign `_ws` to its own dead socket and, once out of retries, tell the
   * webview the connection closed — dropping a working session back to the
   * connect form.
   */
  private _connectToServer(wsUrl: string, retryCount = 0, gen?: number): void {
    const maxRetries = 40; // retry for up to ~40 seconds while server starts
    const myGen = gen ?? ++this._connectGen;
    if (myGen !== this._connectGen) return; // superseded while this retry waited

    const ws = new WebSocket(wsUrl);
    this._ws = ws;

    ws.on("open", () => {
      if (myGen !== this._connectGen) {
        ws.close();
        return;
      }
      // Flush any messages queued before the connection was ready
      for (const m of this._pendingMessages) {
        ws.send(m);
      }
      this._pendingMessages = [];
    });

    ws.on("message", (data: WebSocket.RawData) => {
      if (myGen !== this._connectGen) return;
      // Forward Python server messages → React webview
      const text = data.toString();
      this._view?.webview.postMessage({ type: "ws", payload: text });
      // Read by the host as well as forwarded: one of these messages changes who owns
      // the server process, which is this layer's business and not the webview's.
      this._noteOwnership(text);
      // Surface a native VS Code notification when the chat isn't in view.
      this._maybeNotify(text);
    });

    ws.on("close", () => {
      // A socket we replaced ourselves (headless re-attach) must not drive the
      // retry/teardown of the one that took its place.
      if (myGen !== this._connectGen || this._ws !== ws) return;
      const stillRunning = serverProcess && !serverProcess.killed;
      if (retryCount < maxRetries && stillRunning) {
        // Server still starting up — retry after 2 seconds
        setTimeout(() => this._connectToServer(wsUrl, retryCount + 1, myGen), 2000);
      } else {
        // In attach mode there is no server log to consult, so the reason the
        // connection never came up would otherwise go unrecorded entirely.
        this._attachLog?.appendLine(
          `Nothing answered at ${wsUrl}. That address comes from the "mimir.wsUrl" ` +
          `setting; clear it (check the workspace's .vscode/settings.json) to have ` +
          `MIMIR start its own server instead.`
        );
        // Notify webview — no auto-reconnect (user must click Connect again)
        this._view?.webview.postMessage({ type: "ws_closed" });
      }
    });

    ws.on("error", () => {
      if (myGen !== this._connectGen) return;
      // close fires immediately after error (which handles reconnect/teardown);
      // surface a distinct error signal so the webview can show an error state.
      this._view?.webview.postMessage({ type: "ws_error" });
    });
  }

  // Timestamp of the last notification, used to throttle bursts (e.g. several
  // approvals arriving back-to-back should not spam a stack of toasts).
  private _lastNotifyAt = 0;
  // Cards already announced, so two conversations asking together get a toast each and
  // neither is announced twice. Keyed by card id, which is a uuid.
  private _notifiedPrompts = new Set<string>();

  /**
   * Show a native VS Code notification for milestone events (task finished or
   * user action required) — but only when the user isn't already looking at the
   * chat. "Not looking" means the VS Code window is unfocused OR the chat view
   * is hidden. Clicking the notification focuses the chat.
   */
  /** Open a conversation from outside the webview — the notification's own action.
   *
   *  Sent straight down the socket rather than asked of the webview: the pane may not be
   *  loaded, which is the situation that produced the notification in the first place.
   *  The webview learns of the switch the usual way, from the session_loaded that follows.
   */
  private _switchTo(sessionId: string): void {
    const frame = JSON.stringify({ type: "switch_session", session_id: sessionId });
    if (this._ws && this._ws.readyState === WebSocket.OPEN) {
      this._ws.send(frame);
    } else {
      this._pendingMessages.push(frame);
    }
  }

  private _maybeNotify(payload: string): void {
    const cfg = vscode.workspace.getConfiguration("mimir");
    if (!(cfg.get<boolean>("notifications.enabled") ?? true)) {
      return;
    }

    let msg: {
      type?: string; text?: string; cancelled?: boolean; summary?: string;
      job_key?: string; state?: string; id?: string;
      session_id?: string; session_title?: string;
    };
    try {
      msg = JSON.parse(payload);
    } catch {
      return;
    }
    if (!msg || typeof msg.type !== "string") {
      return;
    }

    // Only notify when the chat isn't in front of the user.
    const chatInView = (this._view?.visible ?? false) && vscode.window.state.focused;
    if (chatInView) {
      return;
    }

    let title: string | undefined;
    let kind: "info" | "warn" = "info";
    switch (msg.type) {
      case "answer":
        // Final answer to the user = task completed (ignore cancelled turns).
        if (msg.cancelled) { return; }
        title = "MIMIR a terminé la tâche.";
        kind = "info";
        break;
      // A card names the conversation that raised it: several conversations run at once,
      // and one may be asking while the user reads another — or while the pane is closed,
      // which is the case this notification exists for.
      case "approval":
        title = msg.session_title
          ? `« ${msg.session_title} » attend votre approbation.`
          : "MIMIR attend votre approbation.";
        kind = "warn";
        break;
      case "user_question":
        title = msg.session_title
          ? `« ${msg.session_title} » a une question pour vous.`
          : "MIMIR a une question pour vous.";
        kind = "warn";
        break;
      case "todo_prompt":
        title = "MIMIR a besoin de votre intervention.";
        kind = "warn";
        break;
      case "job_complete":
        // A detached background run reached a terminal state; the session that
        // launched it auto-resumes, which is not necessarily the one on screen.
        if (msg.state === "crashed") {
          title = `Tâche en arrière-plan « ${msg.job_key ?? ""} » terminée en échec.`;
          kind = "warn";
        } else if (msg.state === "unknown") {
          // Not a success reported quietly: the run stopped being trackable, and
          // saying "terminée" here would claim an outcome nobody observed.
          title = `Tâche en arrière-plan « ${msg.job_key ?? ""} » : suivi perdu.`;
          kind = "warn";
        } else {
          title = `Tâche en arrière-plan « ${msg.job_key ?? ""} » terminée.`;
          kind = "info";
        }
        break;
      case "job_checkin":
        // A periodic bulletin, not an ending: the runs are still going. Deliberately
        // quiet — the point of a check-in is that nothing has happened yet, and a
        // notification every time would train the user to ignore the ones that matter.
        return;
      default:
        return;
    }

    // A card is announced once per card, not once per 2s window. The window stops a burst
    // of progress turning into a burst of toasts; applied to cards it would swallow the
    // second of two conversations asking together, and that one waits for ever with
    // nothing said about it.
    const isPrompt = msg.type === "approval" || msg.type === "user_question";
    if (isPrompt) {
      const key = `${msg.type}:${msg.id ?? ""}:${msg.session_id ?? ""}`;
      if (this._notifiedPrompts.has(key)) {
        return;
      }
      this._notifiedPrompts.add(key);
      // Bounded: the ids are uuids and never recur, so nothing ever leaves on its own.
      if (this._notifiedPrompts.size > 200) {
        this._notifiedPrompts.clear();
      }
    } else {
      const now = Date.now();
      if (now - this._lastNotifyAt < 2000) {
        return;
      }
      this._lastNotifyAt = now;
    }

    // Two ways in, because a card raised elsewhere needs more than the pane: focusing
    // the chat shows whichever conversation was last open, which may not be the one
    // asking.
    const open = "Ouvrir le chat";
    const goThere = "Ouvrir la conversation";
    const actions = isPrompt && msg.session_id ? [goThere, open] : [open];
    const show = kind === "warn"
      ? vscode.window.showWarningMessage
      : vscode.window.showInformationMessage;
    show(title, ...actions).then((choice) => {
      if (choice === goThere && msg.session_id) {
        this._switchTo(msg.session_id);
      }
      if (choice === goThere || choice === open) {
        vscode.commands.executeCommand("mimir.chatView.focus");
      }
    });
  }

  // Release the ws_server this window owns so a fresh connect always starts from a
  // clean slate. The spawn command `exec`s python, so the process we track is the
  // server itself and killing it frees its port — no other window is touched.
  //
  // Three are not ours to end, each for its own reason: one we only attached to
  // (`mimir.wsUrl`, or a server another window started), where `serverProcess` is
  // undefined anyway; one that has detached, which was deliberately kept going; and
  // one already gone. In those cases the socket is dropped and the process left alone.
  private _teardownServer(): void {
    // The socket belongs to the process being released: retiring the generation
    // stops its retry chain from outliving it and hunting a port nobody serves.
    this._connectGen++;
    this._logTail?.dispose();
    this._logTail = undefined;
    this._ws?.close();
    this._ws = undefined;
    if (!serverDetached && serverProcess && !serverProcess.killed) {
      serverProcess.kill();
    }
    serverProcess = undefined;
  }

  /**
   * Start the WS server here and connect to it.
   *
   * The server always runs on the machine VS Code runs on; *baseUrl* points it at
   * an LLM endpoint that is already serving (vLLM, Ray Serve or Ollama), wherever
   * that is.
   * Anthropic needs no URL at all — the hosted API is reached over the network
   * with the key from the form or the environment.
   */
  /**
   * Connect, starting a server only if this workspace does not already have one.
   *
   * The check is not an optimisation. Two servers on one workspace share its sessions
   * directory, so both append to the same journal and both derive `seq` from it: the
   * numbering collides, and a client attached to one sees nothing of the turn running
   * in the other — a conversation whose tools run and never appear, until a reconnect
   * lands on the right server and replays them. The server refuses the second claim
   * itself, which is the guarantee; this is what keeps the ordinary path from relying
   * on being refused.
   *
   * Every path that would start a server asks this first — auto-connect through
   * `_attachToRunningServer`, and this one through the same call.
   */
  private async _startServerAndConnect(
    model: string,
    backend = "vllm",
    baseUrl = "http://127.0.0.1:8000",
    anthropicApiKey = "",
    { silent = false }: { silent?: boolean } = {},
  ): Promise<void> {
    const cfg = vscode.workspace.getConfiguration("mimir");

    if (await this._attachToRunningServer({ silent })) return;

    // Attach mode: an explicit `mimir.wsUrl` means the user runs the server
    // themselves (by hand, or on another host), so we connect and start nothing.
    // That server is not ours, so it is never torn down either.
    const override = (cfg.get<string>("wsUrl") ?? "").trim();
    if (override) {
      // Attach mode starts nothing, so it never reaches the server log below. Say
      // so in that same channel anyway: a stray `mimir.wsUrl` (easily left behind
      // in a workspace's .vscode/settings.json) otherwise silently disables the
      // whole spawn path, and the connect form just reappears with no trace of why.
      const attachLog = vscode.window.createOutputChannel("MIMIR Server");
      if (!silent) attachLog.show();
      attachLog.appendLine(
        `Attaching to ${override} — no server is started here because the ` +
        `"mimir.wsUrl" setting is set. Clear it to let MIMIR start its own server.`
      );
      this._attachLog = attachLog;
      this._teardownServer();
      this._wsUrl = override;
      this._connectToServer(override);
      return;
    }
    // A spawned connect is not attached to anything.
    this._attachLog = undefined;

    // Clean slate: a server left over from a previous connect (possibly on another
    // backend) is ours, and nothing else should be left holding a port.
    this._teardownServer();

    const pythonPath = resolvePython();
    const cwd = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? process.cwd();

    const outputChannel = vscode.window.createOutputChannel("MIMIR Server");
    // A connect the user clicked shows its log; one we started at VS Code launch
    // stays out of the way (the channel is still there to open by hand).
    if (!silent) outputChannel.show();

    const backendArgs =
      backend === "vllm" ? ` --backend vllm --vllm-base-url ${baseUrl}`
      : backend === "ray" ? ` --backend ray --ray-base-url ${baseUrl}`
      : backend === "ollama" ? ` --backend ollama --ollama-base-url ${baseUrl}`
      : backend === "anthropic" ? " --backend anthropic"
      : "";
    // `--port 0`: the OS picks a free port, so two VS Code windows never contend for
    // one — the server publishes the port it actually bound and we connect to that.
    // `exec` replaces the shell with python, so `serverProcess.kill()` reaches the
    // server itself rather than orphaning it on its port.
    //
    // Its output goes to a file, and this is not only for readability. A pipe held by
    // this extension host is a tether: when the host goes, the next write here takes a
    // SIGPIPE, so a server meant to outlive the window would die the first time it
    // logged anything. A file has no reader to lose.
    const serverLog = logPath(cwd, new Date().toISOString().replace(/[:.]/g, "-"));
    const quotedLog = `'${serverLog.replace(/'/g, "'\\''")}'`;
    const spawnCmd =
      `mkdir -p -- "$(dirname -- ${quotedLog})" && ` +
      `exec ${pythonPath} -m mimir.client.ui.ws.ws_server --port 0` +
      `${model ? ` --model ${model}` : ""}${backendArgs} >> ${quotedLog} 2>&1`;
    // Log the command only — the Claude API key is injected via env below and is
    // deliberately kept out of this string so it never lands in the output channel.
    outputChannel.appendLine(`Starting server: ${spawnCmd}`);

    // Internal HTTPS vLLM / Ray Serve routes are often served behind a private
    // CA; when the user disables cert verification, propagate VLLM_VERIFY_SSL so
    // /v1/models model-resolution and chat requests don't hit CERTIFICATE_VERIFY_FAILED.
    const verifyEnv = cfg.get<boolean>("vllmVerifySsl", true) ? {} : { VLLM_VERIFY_SSL: "0" };
    // A router in front of vLLM need not serve /tokenize; turning it off spares every
    // process (sub-agents included) the request, and the retries when it times out.
    const tokenizeEnv = cfg.get<boolean>("vllmTokenize", true) ? {} : { MIMIR_VLLM_TOKENIZE: "0" };
    // An endpoint that does not report max_model_len in /v1/models leaves the client
    // on its static 200K default; this setting is the override. The two env names are
    // the vLLM and Ray Serve escape hatches — only the active backend reads its own.
    const maxLen = cfg.get<number>("maxModelLen", 0) ?? 0;
    const maxLenEnv = maxLen > 0
      ? { MIMIR_VLLM_MAX_MODEL_LEN: String(maxLen), MIMIR_RAY_MAX_MODEL_LEN: String(maxLen) }
      : {};
    // An HTTP proxy silently swallows requests to an on-prem endpoint, so
    // ws_server would hang on model resolution before ever binding its port.
    const noProxyEnv = backend === "anthropic" ? {} : noProxyFor(baseUrl);
    // Only override ANTHROPIC_API_KEY when the webview actually supplied one;
    // otherwise inherit whatever is already exported (so users who set the key in
    // their shell don't have to retype it in the form).
    const anthropicEnv =
      backend === "anthropic" && anthropicApiKey ? { ANTHROPIC_API_KEY: anthropicApiKey } : {};
    serverProcess = cp.spawn("bash", ["-c", spawnCmd], {
      cwd,
      // Anchor the agent's per-workspace state dir (.mimir) and the file-server
      // root to the opened workspace, regardless of the process cwd. The base
      // env is mimirServerEnv(): the user's PYTHONHOME/PYTHONPATH never reach
      // the server's interpreter (see there).
      env: { ...mimirServerEnv(), MCP_FILES_ROOT: cwd, ...noProxyEnv, ...verifyEnv, ...tokenizeEnv, ...maxLenEnv, ...anthropicEnv },
      // Its own process session, from birth. Nothing about this window's teardown can
      // then reach it implicitly — not a process-group signal, not a SIGHUP, not the
      // editor tidying up its tree — so the only thing that ends it is the explicit
      // SIGTERM below, which `deactivate()` skips once it has detached. Arranging this
      // *after* the fact, by having the server leave the group itself, depends on it
      // not already being a group leader, and a detachment that quietly does not hold
      // is worse than none.
      detached: true,
      stdio: "ignore",
    });
    // So this window's exit is not waited on by Node for a process it no longer owns.
    serverProcess.unref();

    const spawned = serverProcess;
    outputChannel.appendLine(`Output: ${serverLog}`);
    this._tailLog(outputChannel, serverLog);

    serverProcess.on("exit", (code) => {
      if (serverProcess !== spawned) return;
      outputChannel.appendLine(`\nServer exited (code ${code}) — see ${serverLog}`);
      serverProcess = undefined;
      // Nothing left to catch a webview up on — don't replay "connecting", and
      // don't offer the models of an endpoint that is no longer being served.
      this._pendingAutoConnect = undefined;
      this._autoConnectModels = undefined;
      this._view?.webview.postMessage({ type: "ws_closed" });
    });

    // The address is not knowable in advance (the OS assigns the port) and there is no
    // pipe to read it from, so it is taken from the registry the server publishes once
    // its socket is bound. Everything before that — MCP handshakes, model resolution —
    // can take a while on a cold start.
    const entry = await waitForServer(cwd, serverProcess.pid);
    if (serverProcess !== spawned && entry === undefined) return;
    if (!entry) {
      outputChannel.appendLine(
        "\nServer did not publish a listening address within 120s — giving up. " +
        `Check the endpoint above is reachable, then connect again. Its log: ${serverLog}`
      );
      this._pendingAutoConnect = undefined;
      this._view?.webview.postMessage({ type: "ws_closed" });
      return;
    }
    if (entry.pid !== serverProcess?.pid) {
      // Ours stood down: this workspace already had a server, and starting a second
      // would have both write the same session journal.
      outputChannel.appendLine(
        `\nThis workspace already had a server (pid ${entry.pid}); attached to it.`);
      serverProcess = undefined;
    }
    this._wsUrl = entry.url;
    this._connectToServer(entry.url);
  }

  /**
   * Mirror a server's log file into its output channel.
   *
   * A detached server writes to a file rather than a pipe, so the channel is a reader
   * of that file rather than of the process. Polled on a timer: the file is appended to
   * by a process in another session, and a watcher adds nothing a cheap stat does not
   * already give.
   */
  private _tailLog(channel: vscode.OutputChannel, file: string): void {
    this._logTail?.dispose();
    let offset = 0;
    const timer = setInterval(() => {
      try {
        const size = fs.statSync(file).size;
        if (size < offset) offset = 0;      // truncated or replaced
        if (size === offset) return;
        const fd = fs.openSync(file, "r");
        try {
          const buf = Buffer.alloc(size - offset);
          fs.readSync(fd, buf, 0, buf.length, offset);
          offset = size;
          channel.append(buf.toString());
        } finally {
          fs.closeSync(fd);
        }
      } catch {
        // Not written yet, or gone. Either way there is nothing to mirror.
      }
    }, 500);
    this._logTail = { dispose: () => clearInterval(timer) };
    _stopLogTail = this._logTail;
  }

  /**
   * Ask the endpoint what models it serves and hand the list to the webview.
   *
   * Runs here rather than in React because the webview's CSP forbids HTTP.
   * A failure is reported as text under the address field, never as a modal: the
   * user can still connect (the server resolves the served model itself).
   */
  private async _sendModels(backend: string, baseUrl: string): Promise<void> {
    if (!ADDRESSED_BACKENDS.includes(backend)) {
      return;
    }
    const verifySsl = vscode.workspace.getConfiguration("mimir").get<boolean>("vllmVerifySsl", true);
    const seq = ++this._modelProbeSeq;
    const current = () => seq === this._modelProbeSeq;
    try {
      const models = await fetchModels(backend as DiscoverableBackend, baseUrl, verifySsl);
      (this._modelLog ??= vscode.window.createOutputChannel("MIMIR Model Discovery")).appendLine(
        `Model list from ${baseUrl}: ${models.length ? models.join(", ") : "(none named)"}`,
      );
      if (!current()) return;
      this._view?.webview.postMessage({ type: "models", backend, models });
    } catch (err) {
      const reason = err instanceof Error ? err.message : String(err);
      // Also to the output channel: the panel shows one line under the address,
      // which the user may have moved past by the time they come looking for why
      // the list was empty.
      (this._modelLog ??= vscode.window.createOutputChannel("MIMIR Model Discovery")).appendLine(
        `Model list from ${baseUrl} failed: ${reason}`,
      );
      if (!current()) return;
      // The panel gets the plain-words version; the raw reason stays in the log.
      this._view?.webview.postMessage({
        type: "models", backend, models: [], error: explainFetchError(err, baseUrl),
      });
    }
  }

  private _handleFromWebview(msg: unknown): void {
    const m = msg as Record<string, unknown>;

    if (m.type === "open_file") {
      const rel = m.file as string | undefined;
      if (rel) {
        const roots = vscode.workspace.workspaceFolders;
        const base  = roots?.[0]?.uri.fsPath ?? process.cwd();
        const abs   = require("path").isAbsolute(rel)
          ? rel
          : require("path").join(base, rel);
        const uri = vscode.Uri.file(abs);
        const line = typeof m.line === "number" ? m.line : undefined;
        const endLine = typeof m.end_line === "number" ? m.end_line : line;
        vscode.workspace.openTextDocument(uri).then(
          (doc) => {
            if (line === undefined) {
              void vscode.window.showTextDocument(doc, { preview: true });
              return;
            }
            // Clamped: the file may have changed since the tool touched it.
            const last = doc.lineCount - 1;
            const start = Math.min(Math.max(line - 1, 0), last);
            const end = Math.min(Math.max((endLine ?? line) - 1, start), last);
            const range = new vscode.Range(start, 0, end, doc.lineAt(end).text.length);
            void vscode.window.showTextDocument(doc, {
              preview: true,
              viewColumn: vscode.ViewColumn.One,
              selection: range,
            }).then((editor) => {
              editor.revealRange(range, vscode.TextEditorRevealType.InCenterIfOutsideViewport);
            });
          },
          () => vscode.window.showWarningMessage(`MIMIR: cannot open ${rel}`)
        );
      }
      return;
    }

    if (m.type === "open_preview") {
      // Open a file the agent wrote (e.g. a plan .md) for reading. Markdown
      // files render in VS Code's Markdown preview; anything else falls back to
      // a normal editor tab.
      const rel = m.file as string | undefined;
      if (rel) {
        const roots = vscode.workspace.workspaceFolders;
        const base  = roots?.[0]?.uri.fsPath ?? process.cwd();
        const abs   = require("path").isAbsolute(rel)
          ? rel
          : require("path").join(base, rel);
        if (/\.mdx?$/i.test(abs)) {
          _showPlanPreview(abs);
        } else {
          const uri = vscode.Uri.file(abs);
          vscode.workspace.openTextDocument(uri).then(
            (doc) => vscode.window.showTextDocument(doc, { preview: true }),
            () => vscode.window.showWarningMessage(`MIMIR: cannot open ${rel}`)
          );
        }
      }
      return;
    }

    if (m.type === "open_diff") {
      const rel        = m.file as string | undefined;
      const newContent = m.new_content as string | undefined;
      if (rel) {
        const roots = vscode.workspace.workspaceFolders;
        const base  = roots?.[0]?.uri.fsPath ?? process.cwd();
        const abs   = require("path").isAbsolute(rel)
          ? rel
          : require("path").join(base, rel);
        const basename = require("path").basename(rel);
        const currentUri = vscode.Uri.file(abs);

        if (newContent !== undefined) {
          // Store proposed content under the absolute path as key, then open a
          // diff editor: left = current file on disk (or empty if new), right = proposed content.
          _diffProposedContent.set(abs, newContent);
          const proposedUri = vscode.Uri.from({ scheme: "mimir-diff", path: abs });

          // Check if the file already exists; if not, use an empty virtual doc
          // as the left side so VS Code doesn't throw "nonexistent file".
          const fs = require("fs") as typeof import("fs");
          const fileExists = fs.existsSync(abs);
          if (fileExists) {
            vscode.commands.executeCommand(
              "vscode.diff",
              currentUri,
              proposedUri,
              `${basename}: Current ↔ Proposed`,
              { preview: true }
            );
          } else {
            // New file — open the proposed content directly (no empty-vs-new diff).
            vscode.workspace.openTextDocument(proposedUri).then(
              (doc) => vscode.window.showTextDocument(doc, { preview: true }),
              () => vscode.window.showWarningMessage(`MIMIR: cannot preview new file ${rel}`)
            );
          }
        } else if (m.patch) {
          // Post-write diff: reconstruct the "before" content by reverse-applying
          // the unified patch, then open left=before right=current.
          const patch = m.patch as string;
          const fs = require("fs") as typeof import("fs");
          let currentContent = "";
          try { currentContent = fs.readFileSync(abs, "utf8"); } catch { /* new file */ }
          const originalContent = _reversePatch(currentContent, patch);
          _diffProposedContent.set(abs + "__original", originalContent);
          const originalUri = vscode.Uri.from({ scheme: "mimir-diff", path: abs + "__original" });
          vscode.commands.executeCommand(
            "vscode.diff",
            originalUri,
            currentUri,
            `${basename}: Before ↔ After`,
            { preview: true }
          );
        } else {
          // No patch or proposed content — fall back to opening the file directly.
          vscode.workspace.openTextDocument(currentUri).then(
            (doc) => vscode.window.showTextDocument(doc, { preview: true }),
            () => vscode.window.showWarningMessage(`MIMIR: cannot open ${rel}`)
          );
        }
      }
      return;
    }

    if (m.type === "open_patch") {
      // Open a single syntax-highlighted .diff virtual document (review window style).
      const rel  = m.file as string | undefined;
      const patch = m.patch as string | undefined;
      if (rel && patch) {
        const roots = vscode.workspace.workspaceFolders;
        const base  = roots?.[0]?.uri.fsPath ?? process.cwd();
        const abs   = require("path").isAbsolute(rel) ? rel : require("path").join(base, rel);
        const basename = require("path").basename(rel);
        // Store patch under a .diff-suffixed key so the language server detects
        // the diff language and applies green/red syntax highlighting.
        const patchKey = abs + ".diff";
        _diffProposedContent.set(patchKey, patch);
        const patchUri = vscode.Uri.from({ scheme: "mimir-diff", path: patchKey });
        vscode.workspace.openTextDocument(patchUri).then(
          (doc) => vscode.window.showTextDocument(doc, { preview: true }),
          () => vscode.window.showWarningMessage(`MIMIR: cannot open patch for ${rel}`)
        );
      }
      return;
    }

    if (m.type === "disconnect") {
      this._ws?.close();
      this._ws = undefined;
      this._logTail?.dispose();
      this._logTail = undefined;
      // A detached server is not this window's to end. Disconnecting from one is
      // leaving the room, not turning the lights off: the run was deliberately kept
      // going, and the panel offered to keep it going on this very click.
      if (!serverDetached && serverProcess && !serverProcess.killed) {
        serverProcess.kill();
      }
      serverProcess = undefined;
      this._view?.webview.postMessage({ type: "ws_closed" });
      return;
    }

    if (m.type === "get_config") {
      // The webview's mount handshake: the one point where it is certainly
      // listening, so it is also where a connect it missed is replayed.
      void this._sendConfig();
      this._announceModels();
      this._resumeAutoConnect();
      return;
    }

    if (m.type === "fetch_models") {
      void this._sendModels(
        (m.backend as string | undefined) ?? "vllm",
        (m.baseUrl as string | undefined) ?? "",
      );
      return;
    }

    if (m.type === "connect") {
      const model = (m.model as string | undefined) ?? "";
      const backend = (m.backend as string | undefined) ?? "vllm";
      const baseUrl = (m.baseUrl as string | undefined) ?? "http://127.0.0.1:8000";
      // Claude API key from the webview. Kept in-process only: passed to the
      // ws_server via the ANTHROPIC_API_KEY env var (never a CLI arg or setting),
      // so it never reaches the process list, the output channel, or disk.
      const anthropicApiKey = (m.anthropicApiKey as string | undefined) ?? "";
      const remember = m.remember === true;

      // The endpoints with an address resolve the served model themselves when none
      // is picked, so only the hosted Claude API needs an explicit one.
      if (!model && backend === "anthropic") {
        vscode.window.showErrorMessage("MIMIR: select a model before connecting.");
        return;
      }

      // "Remember this address" — store the endpoint (never the key) so the next
      // window can reconnect on its own; unchecking it forgets the stored one.
      if (remember && ADDRESSED_BACKENDS.includes(backend)) {
        void this.memento.update(REMEMBERED_KEY, { backend, baseUrl, model });
      } else {
        void this.memento.update(REMEMBERED_KEY, undefined);
      }

      // A hand-typed connect supersedes any auto-connect still being replayed.
      // The form ran its own probe, so the webview already holds that list.
      this._pendingAutoConnect = undefined;
      this._autoConnectModels = undefined;
      this._autoConnectStarted = true;
      void this._startServerAndConnect(model, backend, baseUrl, anthropicApiKey)
        .catch((err) => {
          vscode.window.createOutputChannel("MIMIR Server").appendLine(
            `Starting the server failed: ${err instanceof Error ? err.message : String(err)}`);
          this._view?.webview.postMessage({ type: "ws_closed" });
        });
      return;
    }

    if (m.type === "ws_send") {
      // React wants to send a message to the Python server
      const payload = m.payload as string;
      // Asking to detach is enough to stop killing, before any reply comes back.
      // Otherwise there is a window — the round trip — in which the user has clicked
      // "keep it going", the badge has not changed yet, and closing the editor still
      // ends the run. The two outcomes are not symmetric: a server left running that
      // failed to detach is findable through the registry and endable with the stop
      // command, while a server killed after the user asked to keep it is work gone.
      if (payload.includes('"detach"')) {
        try {
          const parsed = JSON.parse(payload) as { type?: string; enabled?: boolean };
          // `enabled: false` is the user taking the decision back, and that one waits
          // for the server's answer: acting on the request would stop guarding a
          // server still believed detached on the other side.
          if (parsed.type === "detach" && parsed.enabled !== false) {
            serverDetached = true;
          }
        } catch {
          // Not ours to parse; leave the flag alone.
        }
      }
      if (this._ws?.readyState === WebSocket.OPEN) {
        this._ws.send(payload);
      } else {
        this._pendingMessages.push(payload);
      }
    }
  }
}

/**
 * Stop the server this workspace has, detached or not.
 *
 * The counterpart of leaving one running: a detached server is no longer killed by
 * closing the window, so there has to be a way to end it on purpose. It is signalled
 * rather than asked over the socket, because the window that wants it stopped may not
 * be connected to it — that is the whole situation this exists for.
 *
 * SIGTERM, which lands on the server's own handler and takes the ordinary exit: the one
 * that unwinds each agent's exit stack and so reaps the MCP servers. A SIGKILL here
 * would leave up to sixty orphaned interpreters behind, which is precisely the thing
 * that path exists to prevent.
 *
 * Confirmed first, with what is actually running named in the prompt. "Stop the server"
 * is cheap to type and can end a two-hour build, so the decision is made with the facts
 * in front of the user rather than after.
 */
async function stopServer(): Promise<void> {
  const cwd = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? process.cwd();
  const entry = await findLiveServer(cwd);
  if (!entry) {
    vscode.window.showInformationMessage(
      "No MIMIR server is running for this workspace."
    );
    return;
  }
  const what = entry.detached
    ? `the detached MIMIR server (pid ${entry.pid})`
    : `the MIMIR server (pid ${entry.pid})`;
  const answer = await vscode.window.showWarningMessage(
    `Stop ${what}? Any turn still running, and any background job it is waiting on, ` +
    `ends with it.`,
    { modal: true },
    "Stop server"
  );
  if (answer !== "Stop server") return;
  try {
    process.kill(entry.pid, "SIGTERM");
  } catch (err) {
    vscode.window.showErrorMessage(
      `Could not stop pid ${entry.pid}: ${(err as Error).message}`
    );
    return;
  }
  serverDetached = false;
  serverProcess = undefined;
  vscode.window.showInformationMessage(`Asked pid ${entry.pid} to stop.`);
}

// ── Optional server lifecycle ─────────────────────────────────────────────────

function startServer(context: vscode.ExtensionContext): void {
  const pythonPath = resolvePython();

  if (serverProcess && !serverProcess.killed) {
    vscode.window.showInformationMessage("MIMIR WS server is already running.");
    return;
  }

  const outputChannel = vscode.window.createOutputChannel("MIMIR Server");
  outputChannel.show();

  const cwd = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? process.cwd();

  // A fixed port here on purpose: this command exists to run a server you then
  // point `mimir.wsUrl` at, and an OS-assigned port could not be written down in a
  // setting. If 8765 is taken, the bind error shows up in the output channel.
  // `exec` so the process we track — and later kill — is the server, not the shell.
  const spawnCmd = `exec ${pythonPath} -m mimir.client.ui.ws.ws_server --port 8765`;

  // Endpoints that do not report max_model_len in /v1/models would otherwise leave
  // the client on its static 200K default; honor the same override the Connect path
  // applies, so the window does not depend on how the server was started.
  const maxLen = vscode.workspace.getConfiguration("mimir").get<number>("maxModelLen", 0) ?? 0;
  const maxLenEnv = maxLen > 0
    ? { MIMIR_VLLM_MAX_MODEL_LEN: String(maxLen), MIMIR_RAY_MAX_MODEL_LEN: String(maxLen) }
    : {};

  serverProcess = cp.spawn("bash", ["-c", spawnCmd], {
    cwd,
    // Anchor the agent's per-workspace state dir (.mimir) and the file-server
    // root to the opened workspace, regardless of the process cwd. Same
    // python-env isolation as the connect path (see mimirServerEnv).
    env: { ...mimirServerEnv(), MCP_FILES_ROOT: cwd, ...maxLenEnv },
    stdio: ["ignore", "pipe", "pipe"],
  });

  serverProcess.stdout?.on("data", (d: Buffer) => outputChannel.append(d.toString()));
  serverProcess.stderr?.on("data", (d: Buffer) => outputChannel.append(d.toString()));
  serverProcess.on("exit", (code) => {
    outputChannel.appendLine(`\nServer exited (code ${code})`);
    serverProcess = undefined;
  });

  vscode.window.showInformationMessage("MIMIR WS server started.");
  context.subscriptions.push({
    dispose: () => {
      // Not a detached one: this command exists to start a server you then point
      // `mimir.wsUrl` at, and ending it on window close is the opposite of that.
      if (!serverDetached) serverProcess?.kill();
    },
  });
}

// ── Webview HTML ──────────────────────────────────────────────────────────────

function getWebviewHtml(
  webview: vscode.Webview,
  extensionUri: vscode.Uri
): string {
  const scriptUri = webview.asWebviewUri(
    vscode.Uri.joinPath(extensionUri, "dist", "webview.js")
  );
  // Brand assets served from the extension's images/ folder. Exposed to the
  // React app via a small global so components (avatars, connect screen) can
  // reference them through proper webview URIs under the CSP.
  const logoUri = webview.asWebviewUri(
    vscode.Uri.joinPath(extensionUri, "images", "mimir-logo.png")
  );
  const introVideoUri = webview.asWebviewUri(
    vscode.Uri.joinPath(extensionUri, "images", "mimir-intro.mp4")
  );
  const nonce = getNonce();

  return /* html */ `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="Content-Security-Policy"
    content="default-src 'none';
             script-src 'nonce-${nonce}';
             style-src ${webview.cspSource} 'unsafe-inline';
             font-src data:;
             connect-src ws://localhost:* ws://127.0.0.1:*;
             media-src ${webview.cspSource};
             img-src ${webview.cspSource} data:;">
  <title>MIMIR</title>
</head>
<body>
  <div id="root"></div>
  <script nonce="${nonce}">
    window.__MIMIR_ASSETS__ = {
      logo: "${logoUri}",
      introVideo: "${introVideoUri}"
    };
  </script>
  <script nonce="${nonce}" src="${scriptUri}"></script>
</body>
</html>`;
}

function getNonce(): string {
  let text = "";
  const possible =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  for (let i = 0; i < 32; i++) {
    text += possible.charAt(Math.floor(Math.random() * possible.length));
  }
  return text;
}
